# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildLoad < Formula
  desc "build-load - command line tool to create synthetic load for https://github.com/shipwright-io/build"
  homepage "https://github.com/homeport/build-load"
  version "0.7.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/homeport/build-load/releases/download/v0.7.5/build-load_0.7.5_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "45fc57873758f5a09df512e33d19aa6605edcab97796a5e4d77673907bbaa09b"

      def install
        bin.install "build-load"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/build-load/releases/download/v0.7.5/build-load_0.7.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "82008bedd9bee441438056cc0cb5dca91647621ca6112cc1d072cd9905a3360b"

      def install
        bin.install "build-load"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/build-load/releases/download/v0.7.5/build-load_0.7.5_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b7544a5604e26e82fb052139072c260ecf60cb3a04c3c19193698fadf8c3d844"

      def install
        bin.install "build-load"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/build-load/releases/download/v0.7.5/build-load_0.7.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bdb5140e27feec296800e4af8d3083de272877c33b950b9ab3125e2c55cfd5f1"

      def install
        bin.install "build-load"
      end
    end
  end

  test do
    system "#{bin}/build-load version"
  end
end
