# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dyff < Formula
  desc "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  homepage "https://github.com/homeport/dyff"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.7.1/dyff_1.7.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e5e755791a0f7a46db0fa95d422d961887465cd4dde3f37346187d3d46caa856"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/dyff/releases/download/v1.7.1/dyff_1.7.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "232c34157ba98ee63e0c48d6d4458be7aab3e358b70973e2066473d959caf112"

      def install
        bin.install "dyff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/dyff/releases/download/v1.7.1/dyff_1.7.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "58960ad73db78af3bd46ffe219c40271ec040c5156d8f890a823db75561313e5"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.7.1/dyff_1.7.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ebf8627f989e574865ef3f5091343ded89e151358d4698edfd1f853ef70c6422"

      def install
        bin.install "dyff"
      end
    end
  end

  test do
    system "#{bin}/dyff version"
  end
end
