# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dyff < Formula
  desc "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  homepage "https://github.com/homeport/dyff"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d156b5eb5a56a79deab4ed857ed42e1babb5d941a2a7b5ecc79e925ec9074ea8"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "820163c4c382cb9810520a6ca0084363b91aa5858770420d8027c84396b439cb"

      def install
        bin.install "dyff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "46ec6c71fa224144772470febe8f9e245927d584acc649bc765527214827e70d"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab9faa1c5d949a9819bf947f96d0ef620cb73ad91bcfb18c3b96606bf8e2a6f9"

      def install
        bin.install "dyff"
      end
    end
  end

  test do
    system "#{bin}/dyff version"
  end
end
