# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dyff < Formula
  desc "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  homepage "https://github.com/homeport/dyff"
  version "1.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.10.3/dyff_1.10.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "987e31f8ea13fbb9552d89167a837637b0df4bda3f27da7a51ce7cabd382afd6"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/dyff/releases/download/v1.10.3/dyff_1.10.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c81bac7467c51de621328f53d9bf47b25ff0073724f844b5bf93fb4430ed7b5"

      def install
        bin.install "dyff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/dyff/releases/download/v1.10.3/dyff_1.10.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb189119ff95941308edd98792818eb53ee91fd26e265c0e153b9f5e416f20a1"
      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/dyff/releases/download/v1.10.3/dyff_1.10.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4d09249c7d74073de6a2d0b6436e5121095cb1c2447b24486bee7948884414d3"
      def install
        bin.install "dyff"
      end
    end
  end

  test do
    system "#{bin}/dyff version"
  end
end
