# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forklift < Formula
  desc "Container Image manipulation tool"
  homepage "https://github.com/homeport/forklift"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/forklift/releases/download/v0.0.1/forklift_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f3af0919dc00b81ed41135eb041abc1a766f04fb94fd7733af2d69d1d43fba21"

      def install
        bin.install "forklift"
      end
    end
    on_arm do
      url "https://github.com/homeport/forklift/releases/download/v0.0.1/forklift_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fe607bb0b4f9a8cb217398f5d6cffdfcfe6594ed66380c2ac8285c3947d6a583"

      def install
        bin.install "forklift"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/forklift/releases/download/v0.0.1/forklift_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "a34864fae574df7fb19830fd7282222766f8a7ffd3be4e30475d939c4bc42eb6"

        def install
          bin.install "forklift"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/forklift/releases/download/v0.0.1/forklift_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "2ec61a71c3027dde4d7e91874052b7953f5794cd0ea13a3f308e753c4c674510"

        def install
          bin.install "forklift"
        end
      end
    end
  end

  test do
    system "#{bin}/forklift version"
  end
end
