# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCacheProg < Formula
  desc "Experimental Go Cache program implementation using IBM Cloud Object Storage (COS) as cache backend"
  homepage "https://github.com/homeport/go-cache-prog"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/go-cache-prog/releases/download/v0.0.1/go-cache-prog_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f3d24226694c1bdaf5b33c8604b3234e042ffb5e71037ef0fd4949cf7cd7569c"

      def install
        bin.install "go-cache-prog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/go-cache-prog/releases/download/v0.0.1/go-cache-prog_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "144819c85df9f1694c4cb4a9f90a18ff345bcfb19b9366d5cd771df18143d6a8"

      def install
        bin.install "go-cache-prog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/go-cache-prog/releases/download/v0.0.1/go-cache-prog_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "8c3379061f35ef6c576ab405947e82971dd3089bc35d8252cd32e2950a7f70a3"
      def install
        bin.install "go-cache-prog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/go-cache-prog/releases/download/v0.0.1/go-cache-prog_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8f86aa0d43a91f8334667ff06eaeb06262e0602a4662b300f16726ab3e68d8b6"
      def install
        bin.install "go-cache-prog"
      end
    end
  end

  test do
    system "#{bin}/go-cache-prog version"
  end
end
