# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonut < Formula
  desc "gonut - a portable tool to help you verify whether you can push a sample app to a Cloud Foundry"
  homepage "https://github.com/homeport/gonut"
  version "2.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/gonut/releases/download/v2.0.7/gonut_2.0.7_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "497209ca03863192eacd021c868fb61ac509e97cb10a4c13c8870152a615ac6e"

      def install
        bin.install "gonut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/gonut/releases/download/v2.0.7/gonut_2.0.7_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dd3d40b09f67246e3ac9e73c0f0695743bc03e96eb735e79c677ad8de73280a0"

      def install
        bin.install "gonut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/gonut/releases/download/v2.0.7/gonut_2.0.7_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c4419bfc9f38b1ab5e06b4e1f697a9d4e86e182433a1fe6584fc52b0bd593d21"

      def install
        bin.install "gonut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/gonut/releases/download/v2.0.7/gonut_2.0.7_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "353d2ce08f701e9706e1a92d49d8cebb5c438e33638395d14eb1b1e02d3aa73b"

      def install
        bin.install "gonut"
      end
    end
  end

  test do
    system "#{bin}/gonut version"
  end
end
