# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havener < Formula
  desc "/ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks "
  homepage "https://github.com/homeport/havener"
  version "2.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/havener/releases/download/v2.1.0/havener_2.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "441695bdb0f3c9a6e31ec94a0cfb32bc4fb1fa9279df45b5da180dadec9ead38"

      def install
        bin.install "havener"
      end
    end
    on_arm do
      url "https://github.com/homeport/havener/releases/download/v2.1.0/havener_2.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "555f61ccdd3baf41235dfabff1e23345e96193712f6615257a6a648ea98e05a6"

      def install
        bin.install "havener"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.1.0/havener_2.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "005c5e709c5ec7fbe0976c8fa7fde3c00377c004c8a15c1baea458aca2fc9077"

        def install
          bin.install "havener"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.1.0/havener_2.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "439b82a9aae60b20438f98ae4a9716f6481f01f8f28dd084df41bf7a5c122c2b"

        def install
          bin.install "havener"
        end
      end
    end
  end

  test do
    system "#{bin}/havener version"
  end
end
