# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havener < Formula
  desc "/ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks "
  homepage "https://github.com/homeport/havener"
  version "2.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/havener/releases/download/v2.2.1/havener_2.2.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "192605f79d9c2f1e43adec8cc2f82584b402b44056b44dc269339ba7e235c92a"

      def install
        bin.install "havener"
      end
    end
    on_arm do
      url "https://github.com/homeport/havener/releases/download/v2.2.1/havener_2.2.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9c8500ef9272e6084210e1a29577372d7c4283172afeba745c29158dcebaf744"

      def install
        bin.install "havener"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.2.1/havener_2.2.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "ebc1a2897751650ff77c4b7188242dee35dfa695b974fc4bb8329f5afe0c2fef"

        def install
          bin.install "havener"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.2.1/havener_2.2.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "5e2d8f82b516f1e1c1d8e0fa540d90a69d4eedbb782983eade106707219aa435"

        def install
          bin.install "havener"
        end
      end
    end
  end

  test do
    system "#{bin}/havener version"
  end
end
