# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havener < Formula
  desc "/ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks "
  homepage "https://github.com/homeport/havener"
  version "2.2.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/havener/releases/download/v2.2.4/havener_2.2.4_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "39976a0ba8adb13a82afa9002139fee386bcc98e6daca74e62613523bc8a1281"

      def install
        bin.install "havener"
      end
    end
    on_arm do
      url "https://github.com/homeport/havener/releases/download/v2.2.4/havener_2.2.4_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6d129bda2ee13696b4014ec44a1967926ec53691bf9e0ca323af9b946eedaed5"

      def install
        bin.install "havener"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.2.4/havener_2.2.4_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "eb98677b45b5b7d543d4db6a2442fe07d1202a9f19e7519a677b6e209474287a"

        def install
          bin.install "havener"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/havener/releases/download/v2.2.4/havener_2.2.4_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1ed9ebbbf5e8fccc196b4b7325a1732b571406d99f2807881a00304f31fe366d"

        def install
          bin.install "havener"
        end
      end
    end
  end

  test do
    system "#{bin}/havener version"
  end
end
