# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pd < Formula
  desc "pd - command line tool to query PagerDuty for the current on-calls"
  homepage "https://github.com/homeport/pd"
  version "2.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/homeport/pd/releases/download/v2.5.5/pd_2.5.5_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a3862c0ec57c0bd3c7efdf4b6cce726ff7f75c162cb42641fe724f76ac01c4fb"

      def install
        bin.install "pd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/pd/releases/download/v2.5.5/pd_2.5.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "420aedf1b945c91875758cf7277ea8c2ce9a2abbbd2856d2b300f17c62e3c9f5"

      def install
        bin.install "pd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/pd/releases/download/v2.5.5/pd_2.5.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "936ca740e998fa93d589aa7627e11d955418e69ebce9fb0aa2c6d19d88e17304"

      def install
        bin.install "pd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/pd/releases/download/v2.5.5/pd_2.5.5_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ab00d0495c331daf786a8424a08e5d89a3357259ff30d30d7f7f52c9ad0ff99b"

      def install
        bin.install "pd"
      end
    end
  end

  test do
    system "#{bin}/pd version"
  end
end
