# This file was generated by repo/hack/update-formula.sh. DO NOT EDIT.
class Playground < Formula
  desc "Playground project."
  homepage "https://github.com/homeport/playground"
  version "0.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/playground/releases/download/v0.0.6/playground_0.0.6_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f91984ae050f45bef527950f1f451712b044904a1160462b634a5b4e0fce2ca0"

      def install
        bin.install "playground"
      end
    end
    on_arm do
      url "https://github.com/homeport/playground/releases/download/v0.0.6/playground_0.0.6_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "297d4c1cf464c096344c09925c6ec185c275dd3c6f183d63401c6084a4d9b30e"

      def install
        bin.install "playground"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/playground/releases/download/v0.0.6/playground_0.0.6_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "9a0b3d6f7d8967eb06aa5f1c63be340b3785f774c4fb1fe99898c69bb1129c96"

        def install
          bin.install "playground"
        end
      end
    end
  end

  test do
    system "#{bin}/playground"
  end
end
