# This file was generated by /home/runner/work/_temp/744b9ecc-9601-48c8-a84c-9c795b98de8a.sh. DO NOT EDIT.
class Playground < Formula
  desc "Playground project."
  homepage "https://github.com/homeport/playground"
  version "0.0.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/playground/releases/download/v0.0.9/playground_0.0.9_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "35bccdd9ca11a06d003f25e244cf07775cef25905e4e0b041e2c645adf377bd7"

      def install
        bin.install "playground"
      end
    end
    on_arm do
      url "https://github.com/homeport/playground/releases/download/v0.0.9/playground_0.0.9_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7d8499cde77a4f5924eb29da2d59faa5616cb300ddfd7b4b7368153db81755f5"

      def install
        bin.install "playground"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/playground/releases/download/v0.0.9/playground_0.0.9_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "b5d0451e06339b974c834273ac110279cbc83254f45d9e22fd9eae09fd734ac0"

        def install
          bin.install "playground"
        end
      end
    end
  end

  test do
    system "#{bin}/playground"
  end
end
