# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "Tool to retry a command in case it fails"
  homepage "https://github.com/homeport/retry"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/retry/releases/download/v0.1.4/retry_0.1.4_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ef18db8ad0dcac4f39cae213958d4c3c3115585836f5b844d2d0143aebe94568"

      def install
        bin.install "retry"
      end
    end
    on_arm do
      url "https://github.com/homeport/retry/releases/download/v0.1.4/retry_0.1.4_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9790e037b363b06932fcfa6bc58af7fea7c06d03f7c5ef52d08b5f9dada87644"

      def install
        bin.install "retry"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/retry/releases/download/v0.1.4/retry_0.1.4_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "c397c87dbdcee370eb45f6503d99beb5672da271c34a1b0ddb7264f5ea314b01"

        def install
          bin.install "retry"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/retry/releases/download/v0.1.4/retry_0.1.4_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "49d3086ac8e8f8a16d959cc6d0da395cbd313b191ace1a90790bc15b40de106f"

        def install
          bin.install "retry"
        end
      end
    end
  end

  test do
    system "#{bin}/retry true"
  end
end
