# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "Tool to retry a command in case it fails"
  homepage "https://github.com/homeport/retry"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/retry/releases/download/v0.1.8/retry_0.1.8_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e7ab239979860db78dbe55eff5e021cda11fea13bd1732b5bd826054486f0026"

      def install
        bin.install "retry"
      end
    end
    on_arm do
      url "https://github.com/homeport/retry/releases/download/v0.1.8/retry_0.1.8_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e3fec919a551b8c5be80ec8ad75a3f345562f71a68e56129b8460b6cfd0aa4bf"

      def install
        bin.install "retry"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/retry/releases/download/v0.1.8/retry_0.1.8_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "9775b54d18cdcd970eb935f114c9668fdc03055c19710cfa9df0e56c5397dcd9"

        def install
          bin.install "retry"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/retry/releases/download/v0.1.8/retry_0.1.8_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "99cd6010ca10076c5d4a617b8f65f8b6bb97c47e0109aa72d6e470d4677ee08b"

        def install
          bin.install "retry"
        end
      end
    end
  end

  test do
    system "#{bin}/retry true"
  end
end
