# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termshot < Formula
  desc "Creates screenshots based on terminal command output."
  homepage "https://github.com/homeport/termshot"
  version "0.2.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/termshot/releases/download/v0.2.10/termshot_0.2.10_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6fdc90979440546c587054bef824a49ace97ebdb26f3851882f7af66040a2eb5"

      def install
        bin.install "termshot"
      end
    end
    on_arm do
      url "https://github.com/homeport/termshot/releases/download/v0.2.10/termshot_0.2.10_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0eae96664eb2b1893e37bccbd04c756cd217891e5061c21c861221d453163533"

      def install
        bin.install "termshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.10/termshot_0.2.10_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "0a30b9e7a4d9ea4a1588c4bd9b4ebb32c9d59e8155a39c9c6f4b34e247678d3b"

        def install
          bin.install "termshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.10/termshot_0.2.10_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "bc2b736f36603cce9def6048594d3e2ed33f191b1b87a4476458bbfc5f21b9db"

        def install
          bin.install "termshot"
        end
      end
    end
  end

  test do
    system "#{bin}/termshot --version"
  end
end
