# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termshot < Formula
  desc "Creates screenshots based on terminal command output."
  homepage "https://github.com/homeport/termshot"
  version "0.2.12"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/termshot/releases/download/v0.2.12/termshot_0.2.12_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a66757743194a4f2997609c14455227632dd5ecc31c323568190f6f01f8b296b"

      def install
        bin.install "termshot"
      end
    end
    on_arm do
      url "https://github.com/homeport/termshot/releases/download/v0.2.12/termshot_0.2.12_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "363767e252dfceffa4d47dfc71c30d037582d876aa27bcf5ae025be8312673db"

      def install
        bin.install "termshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.12/termshot_0.2.12_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "c6d997a2d948f11cc36f15bdf2f27d44c5cf4c6d2dbde1114f03b9bc486ea32c"

        def install
          bin.install "termshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.12/termshot_0.2.12_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "faee9dda3c8052adcbdd3ffee7fc96baa5f667b6a01b5a0939974538d7369c89"

        def install
          bin.install "termshot"
        end
      end
    end
  end

  test do
    system "#{bin}/termshot --version"
  end
end
