# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termshot < Formula
  desc "Creates screenshots based on terminal command output."
  homepage "https://github.com/homeport/termshot"
  version "0.2.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/termshot/releases/download/v0.2.11/termshot_0.2.11_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "bd75360ff8eb6b91d62a6017d8973663c3a7a638375b5746b84ea27705c09da6"

      def install
        bin.install "termshot"
      end
    end
    on_arm do
      url "https://github.com/homeport/termshot/releases/download/v0.2.11/termshot_0.2.11_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e49337811d441c271aa47bac71b3f09130b9ccce1e4885bc62477c9e60d6f95e"

      def install
        bin.install "termshot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.11/termshot_0.2.11_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "dbb666fbec618139fa38f626f6b4c3a63af3c20ba0f0b2a920ca1982e92532cf"

        def install
          bin.install "termshot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/termshot/releases/download/v0.2.11/termshot_0.2.11_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f6e921c728c8c5e34dab50536cf823f0be1c3fd71b53c56e5f0b1eff65298174"

        def install
          bin.install "termshot"
        end
      end
    end
  end

  test do
    system "#{bin}/termshot --version"
  end
end
