# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yft < Formula
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/dyff"
  version "1.0.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/yft/releases/download/v1.0.7/yft_1.0.7_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "01a08b0412fe9d502050f8aa7f9ce35ab90660eaf1b51818e43005cda6162b0b"

      def install
        bin.install "yft"
      end
    end
    on_arm do
      url "https://github.com/homeport/yft/releases/download/v1.0.7/yft_1.0.7_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5ff2258b9fc8c738ab58c1841cc7b3dc3c8515ff79dc791d42f09359d1bd6ad6"

      def install
        bin.install "yft"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.7/yft_1.0.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e83930f8903837fbb48ed28fda6ec034362284fadbbd03645a4e3cd24223926e"

        def install
          bin.install "yft"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.7/yft_1.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "27d2c8b8ff7a8838ae8ad1d155b645a84d1092d16333d3260d3141936fd15c23"

        def install
          bin.install "yft"
        end
      end
    end
  end

  test do
    system "#{bin}/yft version"
  end
end
