# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yft < Formula
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/dyff"
  version "1.0.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/yft/releases/download/v1.0.10/yft_1.0.10_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a10f3943c465351592f1727212698509fb5ebb1a2f4a5e41609ac605d91a88a2"

      def install
        bin.install "yft"
      end
    end
    on_arm do
      url "https://github.com/homeport/yft/releases/download/v1.0.10/yft_1.0.10_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "226a45c3a977912f909d14f95f29cc6c3f389927bb9b57add04bf280f728f49a"

      def install
        bin.install "yft"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.10/yft_1.0.10_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "118161cdad3ed4948836f976a5d7a15ac62c0541fdf5b848678bfebe4fccad2b"

        def install
          bin.install "yft"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.10/yft_1.0.10_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1acbae3b90e18702e44d3c545b7d48651cf9531481f587a8fdd6cac1c6e1bf3d"

        def install
          bin.install "yft"
        end
      end
    end
  end

  test do
    system "#{bin}/yft version"
  end
end
