# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yft < Formula
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/dyff"
  version "1.0.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/homeport/yft/releases/download/v1.0.11/yft_1.0.11_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "761ee36e95a774377693c0d4488423abe2059cbba206736f37663e565ff53c86"

      def install
        bin.install "yft"
      end
    end
    on_arm do
      url "https://github.com/homeport/yft/releases/download/v1.0.11/yft_1.0.11_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "74b2c926b983b0726d218b586d9bdb79744c8e99d001b24b1c2af90d46556d6e"

      def install
        bin.install "yft"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.11/yft_1.0.11_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "5e52836f3cb6f6287cc021c585677b1c8450a36df1706edd0128fe13d169e143"

        def install
          bin.install "yft"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/homeport/yft/releases/download/v1.0.11/yft_1.0.11_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7a1aa2c323b56b7c312aa152521347014d275d204de3eb2da2f220004e002c3c"

        def install
          bin.install "yft"
        end
      end
    end
  end

  test do
    system "#{bin}/yft version"
  end
end
