# This file was generated by GoReleaser. DO NOT EDIT.
cask "yft" do
  version "1.0.15"

  on_macos do
    on_intel do
      sha256 "33be9e99d72843d953fcb1e6c66e9a3dfd1b552c8e5f60787187659f569e90b4"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0cb21f10cdc21b343c6482183edcec300c39af653cc29ed09700e43ee27eadd5"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00cf227a8a593204bbb4def5b995c7d73efec15842619aabecfac9d41bf0965d"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f96fe5b36884636debfe1e6ced7ae88d269a5b67d2b881500c1b96208328e03d"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yft"
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/dyff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yft"

  # No zap stanza required

end
