# This file was generated by GoReleaser. DO NOT EDIT.
cask "yft" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "f18a23b667cb7b945b6582e46b3b5f863cab9eb4016a663b6310ef52b7eadc35"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "82d966c2a2b781801365492f6232a4f537c67d10b2afc7db594ffd326c432de4"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "fae94bf2464f086693cd4cd3bfd0080e48ee7708ff0f10c67b06cb2977c03a60"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "31645e7327e657aa76be09b5bfd86ca93e43ba551cca4cac84f9223bfe10fa90"
      url "https://github.com/homeport/yft/releases/download/v#{version}/yft_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl
    end
  end

  name "yft"
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/dyff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yft"

  # No zap stanza required

end
